Created primary_color_function
mlhaus/KCC-Intro-Mon-Night pull request #9
Opened 2020-10-19 09:45 UTC by gulten-cicek

2020-10-19 15:26 UTC, mlhaus commented on gulten.py
> +primary_color("primaryColor1, primaryColor2")
Don't put quotation marks around variable names. Only use quotation marks around strings. This should be `primary_color(primaryColor1, primaryColor2) `

2020-10-19 15:27 UTC, mlhaus requested changes
Remove the quotation marks around variable arguments when calling the function.

2020-10-19 16:43 UTC, gulten-cicek commented
I will do it, thank you.
________________________________
From: Marc Hauschildt <notifications@github.com>
Sent: Monday, October 19, 2020 10:27 AM
To: mlhaus/KCC-Intro-Mon-Night <KCC-Intro-Mon-Night@noreply.github.com>
Cc: Cicek, Gulten <gulten-cicek@student.kirkwood.edu>; Author <author@noreply.github.com>
Subject: Re: [mlhaus/KCC-Intro-Mon-Night] Created primary_color_function (#9)


@mlhaus requested changes on this pull request.

Remove the quotation marks around variable arguments when calling the function.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mlhaus/KCC-Intro-Mon-Night/pull/9#pullrequestreview-511887005>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQZSZJXCA7OTLOZAKCWV443SLRLFVANCNFSM4SV425OQ>.

2020-10-28 16:21 UTC, mlhaus commented
You copied the tic-tac-toe code into your gulten.py file. That's not what I wanted you to do.

2020-10-28 16:21 UTC, closed without merging

2020-10-28 17:28 UTC, gulten-cicek commented
Do I have to send tic-tac-toe again?

________________________________
From: Marc Hauschildt <notifications@github.com>
Sent: Wednesday, October 28, 2020 11:21 AM
To: mlhaus/KCC-Intro-Mon-Night <KCC-Intro-Mon-Night@noreply.github.com>
Cc: Cicek, Gulten <gulten-cicek@student.kirkwood.edu>; Author <author@noreply.github.com>
Subject: Re: [mlhaus/KCC-Intro-Mon-Night] Created primary_color_function (#9)


You copied the tic-tac-toe code into your gulten.py file. That's not what I wanted you to do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mlhaus/KCC-Intro-Mon-Night/pull/9#issuecomment-718047738>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQZSZJXDWRQWQYLU7EMJ4OTSNBAJ5ANCNFSM4SV425OQ>.

2020-10-31 01:28 UTC, mlhaus commented
No, it was done as a class in the tic-tac-toe.py file. You need to send your exercise6 code for Chapter 7.